baseURL = "https://tmasumolikebirds96gm-lang.github.io/toyofuku-masaya-archive/"
languageCode = "ja"
title = "日々鳥景アーカイブ"

canonifyURLs = true
relativeURLs = false

[pagination]
  pagerSize = 10

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  author = "豊福雅哉"
  description = "豊福雅哉による動物・野鳥・風景・カメラ・写真のデジタルアーカイブ。都会に生きる生き物の一瞬の記録。"
  google_verify = "f1pRUgA1p1dXFI60_zoCpg1pTOdd3Ve6hD-RL-po7IY"
  images = "/toyofuku-masaya-archive/images"
  x_url = "https://x.com/suzume_l0718"
  portfolio_url = "https://tmasumolikebirds96gm-lang.github.io/masaya-toyofuku/"
  custom_css = ["css/custom.css"]

[markup]
  [markup.goldmark.renderer]
    unsafe = true

  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2

[menu]
  [[menu.main]]
    name = "HOME"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "記事"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "日記"
    url = "/categories/日記/"
    weight = 11
  [[menu.main]]
    name = "野鳥"
    url = "/categories/野鳥/"
    weight = 12
  [[menu.main]]
    name = "動植物"
    url = "/categories/動植物/"
    weight = 13
  [[menu.main]]
    name = "資料"
    url = "/categories/資料/"
    weight = 14
  [[menu.main]]
    name = "紀行"
    url = "/categories/紀行/"
    weight = 15
  [[menu.main]]
    name = "タグ"
    url = "/tags/"
    weight = 20
  [[menu.main]]
    name = "プロフィール"
    url = "/profile/"
    weight = 30
  [[menu.main]]
    name = "連絡"
    url = "/contact/"
    weight = 40

  [[menu.main]]
    name = "検索"
    url = "/search/"
    weight = 50

[outputs]
  home = ["HTML", "RSS", "JSON", "Sitemap"]    